import Head from 'next/head'
import HomePage from '../components/home'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Racing+Sans+One&display=swap" rel="stylesheet"/>
        {/* <script  src="https://kit.fontawesome.com/b7ecb94de9.js"></script> */}
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"/>
      </Head>
      
      <HomePage/>
   </> 
    
  )
}
